services:
  certbot:
    command: sh -c "mkdir -p /etc/letsencrypt/live/blackhole-mainnet.com && openssl req -x509 -newkey rsa:4096 -keyout /etc/letsencrypt/live/blackhole-mainnet.com/privkey.pem -out /etc/letsencrypt/live/blackhole-mainnet.com/fullchain.pem -days 365 -nodes -subj '/CN=blackhole-mainnet.com'"